# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Change_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddItemDialog(object):
    def setupUi(self, AddItemDialog):
        AddItemDialog.setObjectName("AddItemDialog")
        AddItemDialog.resize(480, 224)
        self.gridLayoutWidget = QtWidgets.QWidget(AddItemDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 461, 167))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddItemDialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 190, 161, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(AddItemDialog)
        self.buttonBox.accepted.connect(AddItemDialog.accept)
        self.buttonBox.rejected.connect(AddItemDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddItemDialog)

    def retranslateUi(self, AddItemDialog):
        _translate = QtCore.QCoreApplication.translate
        AddItemDialog.setWindowTitle(_translate("AddItemDialog", "Добавить Товар"))
        self.label_2.setText(_translate("AddItemDialog", "Еденица измерения"))
        self.label_3.setText(_translate("AddItemDialog", "МНН / альтернативное название / группа"))
        self.label.setText(_translate("AddItemDialog", "Наименование"))
