# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oper_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OperationDialog(object):
    def setupUi(self, OperationDialog):
        OperationDialog.setObjectName("OperationDialog")
        OperationDialog.resize(555, 265)
        self.gridLayoutWidget = QtWidgets.QWidget(OperationDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 531, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 8, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox.setAccelerated(True)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setMaximum(1000000000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 6, 1)

        self.retranslateUi(OperationDialog)
        self.buttonBox.accepted.connect(OperationDialog.accept)
        self.buttonBox.rejected.connect(OperationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OperationDialog)

    def retranslateUi(self, OperationDialog):
        _translate = QtCore.QCoreApplication.translate
        OperationDialog.setWindowTitle(_translate("OperationDialog", "Добавить операцию"))
        self.label.setText(_translate("OperationDialog", "Наименование"))
        self.label_4.setText(_translate("OperationDialog", "Кому выдано/приходный документ"))
        self.comboBox.setItemText(0, _translate("OperationDialog", "Приход"))
        self.comboBox.setItemText(1, _translate("OperationDialog", "Расход"))
        self.label_3.setText(_translate("OperationDialog", "Количество"))
        self.label_2.setText(_translate("OperationDialog", "Операция"))
        self.label_5.setText(_translate("OperationDialog", "Дата операции"))
